version: '3'
services:
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=phonebook
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./mysql:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    entrypoint: ["./wait.sh"]
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - ./mysql:/run/mysqld
    depends_on:
      - db